Copy -> Uma copia do array é criada em memoria, mas as 2 matrizes são independentes (Original e Copia)

View -> Não é criada uma copia, ela compartilha os mesmos dados do array original

In [2]:
import numpy as np

In [3]:
array_original = np.array([[1, 2, 3],
                           [4, 5, 6]])

array_original

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# Copy
array_copia = array_original.copy()
array_copia

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
array_copia[0, 0] = 100
array_original

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
# View
array_view = array_original[0:, 0:]
array_view[1, 1] = 99
array_original

array([[ 1,  2,  3],
       [ 4, 99,  6]])