In [1]:
import numpy as np

In [2]:
array = np.array([[10, 20, 30], 
                  [40, 50, 60],
                  [70, 80, 90]])

print(array.ndim) # número de dimensões
print(array.shape) # formato do array
array

2
(3, 3)


array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [4]:
# Buscar elemento na linha 1, coluna 2
elemento = array[1, 2]
print(elemento)

60


In [ ]:
# Pegar dados da primeira linha
linha_0 = array[0] # pega a linha 0
print(linha_0)

[10 20 30]


In [7]:
# Pegar dados da segunda coluna
coluna_1 = array[:, 1] # pega a coluna 1
print(coluna_1)

[20 50 80]


In [8]:
# Fatiando para obter um subarray
subarray = array[0:2, 1:3] # pega as linhas 0 e 1, colunas 1 e 2
subarray

array([[20, 30],
       [50, 60]])

In [9]:
mascara = array > 50
mascara

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [ ]:
# Filtragem booleano
elementos_maiores_que_50 = array[mascara]
print(elementos_maiores_que_50)

[60 70 80 90]


In [11]:
# Modificando elemento na linha 1, coluna 1
array[1, 1] = 100
array

array([[ 10,  20,  30],
       [ 40, 100,  60],
       [ 70,  80,  90]])