In [1]:
import numpy as np

In [2]:
np.__version__

'2.4.2'

In [3]:
arr = np.array([1, 2, 3, 4, 5])

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
soma = arr + 10
print(soma)

[11 12 13 14 15]


In [6]:
multi = arr * 2
print(multi)

[ 2  4  6  8 10]


In [7]:
media = np.mean(arr)
print(media)

3.0
