In [2]:
import numpy as np
from typing import List

In [59]:
# Criando arrays 1D
class Array1D:

    def __init__(self, valores: List[int] | List[str] | np.ndarray):

        self.array = np.array(valores)

    def show(self) -> None:
        print(self.array)

    def concatenate(self, outro_array: "Array1D") -> "Array1D":
        novo_array = np.concatenate((self.array, outro_array.array))
        return Array1D(novo_array.tolist())
    
    def verticalStack(self, arr1: "Array1D", arr2: "Array1D") -> "Array1D":
        table = np.vstack((self.array, arr1.array, arr2.array))
        return Array1D(table)
    
    def mean(self, axis=1) -> "Array1D":
        medias = np.mean(self.array, axis=axis)
        return Array1D(medias)

    
    @classmethod
    def matrizNotas(cls, col1: "Array1D", col2: "Array1D") -> "Array1D":
        matriz = np.column_stack((col1.array, col2.array))
        return cls(matriz)


In [60]:
# Instanciando
array1 = Array1D([1, 2, 3])
array1.show()

array2 = Array1D([4, 5, 6])
array2.show()

[1 2 3]
[4 5 6]


In [61]:
# Concatenando os arrays
novo_array = array1.concatenate(array2)
novo_array.show()

[1 2 3 4 5 6]


In [62]:
# Exemplo real
alunos = Array1D(["Pedro", "Monalysa", "Daniel"])
notas_mat = Array1D([7, 9, 8])
notas_fis = Array1D([10, 10, 9])

tabela = alunos.verticalStack(notas_mat, notas_fis)
tabela.show()

[['Pedro' 'Monalysa' 'Daniel']
 ['7' '9' '8']
 ['10' '10' '9']]


In [63]:
# Horizontal stack {np.column_stack}
tabela = Array1D.matrizNotas(notas_mat, notas_fis)
tabela.show()

[[ 7 10]
 [ 9 10]
 [ 8  9]]


In [64]:
# Media
media1 = tabela.mean()
media1.show()

[8.5 9.5 8.5]
