In [1]:
import numpy as np

In [6]:
# Lista de Dados, como series temporais ou coleções de valores
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d.ndim) # número de dimensões
print(array_1d.shape) # formato do array
array_1d


1
(5,)


array([1, 2, 3, 4, 5])

In [7]:
# Matrizes, tabelas de dados, imagens em escala de cinza
array_2d = np.array([[1,2,3], [4,5,6]])
print(array_2d.ndim) # número de dimensões
print(array_2d.shape) # formato do array
array_2d

2
(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Imagens coloridas, vídeos, dados científicos com múltiplas variáveis
array_3d = np.array([[[1,2], [3,4], [5,6], [7,8]]])
print(array_3d.ndim) # número de dimensões
print(array_3d.shape) # formato do array
array_3d

3
(1, 4, 2)


array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])