In [1]:
import numpy as np

In [2]:
array = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10],
                  [11, 12, 13, 14, 15],
                  [16, 17, 18, 19, 20]])

array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
fatiando_linhas = array[0:2, :] # Fatiando as linhas 0 e 1, pegando todas as colunas
fatiando_linhas

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
fatiando_colunas = array[:, 3:5] # Fatiando as colunas 3 e 4, pegando todas as linhas
fatiando_colunas

array([[ 4,  5],
       [ 9, 10],
       [14, 15],
       [19, 20]])

In [ ]:
subarray_central = array[1:3, 1:4] # Fatiando as linhas 1 e 2, colunas 1 a 3
subarray_central

array([[ 7,  8,  9],
       [12, 13, 14]])

In [7]:
array[1:3, 1:4] = array[1:3, 1:4] * 2
array

array([[ 1,  2,  3,  4,  5],
       [ 6, 14, 16, 18, 10],
       [11, 24, 26, 28, 15],
       [16, 17, 18, 19, 20]])