In [1]:
import numpy as np

In [2]:
array = np.array([1, 2, 3, 4, 5])
array

array([1, 2, 3, 4, 5])

In [3]:
# Somar valores dentro do array
soma = np.add(array, 10)
soma

array([11, 12, 13, 14, 15])

In [4]:
# Subtrair valores dentro do array
subtracao = np.subtract(array, 1)
subtracao

array([0, 1, 2, 3, 4])

In [5]:
# Multiplicar valores dentro do array
produto = np.multiply(array, 2)
produto

array([ 2,  4,  6,  8, 10])

In [6]:
# Dividir valores dentro do array
produto = np.divide(array, 10)
produto

array([0.1, 0.2, 0.3, 0.4, 0.5])

In [ ]:
# Funções trigonometricas
seno = np.sin(array)
print(seno)

cosseno = np.cos(array)
print(cosseno)

tangente = np.tan(array)
print(tangente)

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]


In [10]:
# Funções estatisticas
media = np.mean(array)
print(media)

desvio_padrao = np.std(array)
print(desvio_padrao)

3.0
1.4142135623730951


In [11]:
# Funções de comparação
maior_3 = array > 3
maior_3

array([False, False, False,  True,  True])

In [12]:
# Funções exponenciais
raiz = np.sqrt(array)
print(raiz)

potencia = np.power(array, 2)
print(potencia)

exponencial = np.exp(array)

[1.         1.41421356 1.73205081 2.         2.23606798]
[ 1  4  9 16 25]


In [14]:
# Funções logaritmicas
logaritmo = np.log(array)
logaritmo

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [15]:
# Arrendondamento
arred = np.round(array / 2)
arred

array([0., 1., 2., 2., 2.])