In [2]:
import numpy as np
from typing import List

In [41]:
class Array:

    def __init__(self, vetor: List[int]):
        self.array = np.array(vetor)

    def show(self):
        print(self.array)

    def split(self, splitValue: int) -> "Array":
        splited_array = np.split(self.array, splitValue)
        return Array(splited_array)
    
    def meanRow(self, row: int = 0) -> float:
        media = np.mean(self.array[row])
        return media
    
    def meanAllRows(self) -> list[float]:
        
        medias = np.mean(self.array, axis=1)

        return medias.tolist()


In [42]:
array1 = Array([1, 2, 3, 4, 5, 6])
array1.show()

[1 2 3 4 5 6]


In [43]:
array_dividido = array1.split(3)
array_dividido.show()


[[1 2]
 [3 4]
 [5 6]]


In [44]:
# Exemplo real
temperaturas = Array([22, 21, 23, 25, 20, 19, 21,
                      24, 26, 27, 25, 22,
                      20, 18, 19, 20, 21,
                      22, 23, 25, 27, 29,
                      24, 26, 27, 25, 22,
                      24, 26, 27, 25, 22])

temperaturas.show()

[22 21 23 25 20 19 21 24 26 27 25 22 20 18 19 20 21 22 23 25 27 29 24 26
 27 25 22 24 26 27 25 22]


In [49]:
semanas = temperaturas.split(4)
semanas.show()

[[22 21 23 25 20 19 21 24]
 [26 27 25 22 20 18 19 20]
 [21 22 23 25 27 29 24 26]
 [27 25 22 24 26 27 25 22]]


In [46]:
media0 = semanas.meanRow(0)
print(media0)

21.875


In [47]:
medias = semanas.meanAllRows()
print(medias)

[21.875, 22.125, 24.625, 24.75]
