In [1]:
import numpy as np

In [20]:
class Array:

    def __init__(self, array: list):
        self.array = np.array(array)

    def show(self):
        print(self.array)

    def findPosition(self, valor):
        return np.where(self.array==valor)
    
    def approveds(self, mean):
        approved = np.where(self.array > mean)
        return self.array[approved]
    
    def maxGrade(self):
        return np.max(self.array)
    
    def minGrade(self):
        return np.min(self.array)

In [16]:
array1 = Array([10, 20, 30, 40, 50])
array1.show()

[10 20 30 40 50]


In [17]:
# Pesquisando no array
print(array1.findPosition(30))

(array([2]),)


In [21]:
# Exemplo mais real
notas = Array([55, 67, 72, 48, 90, 85, 60, 50])
notas.show()

[55 67 72 48 90 85 60 50]


In [22]:
# Pesquisar quais alunos foram aprovados
print(notas.approveds(60))

[67 72 90 85]


In [23]:
# Notas maxima e minima
print(notas.maxGrade())
print(notas.minGrade())

90
48
